[package]
name = "acbr_rust"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
num_cpus = "1"
node-bindgen = { version = "5.0" }

[build-dependencies]
node-bindgen = { version = "5.0", features = ["build"] }